DOMAIN = "entertainment_releases"

CONF_API_TOKEN = "api_token"
CONF_REGION = "region"

CONF_THEATRICAL_DAYS = "theatrical_days"
CONF_DIGITAL_DAYS = "digital_days"
CONF_TV_DAYS = "tv_days"
CONF_REFRESH_INTERVAL = "refresh_interval"

DEFAULT_REGION = "US"

DEFAULT_THEATRICAL_DAYS = 7
DEFAULT_DIGITAL_DAYS = 1
DEFAULT_TV_DAYS = 1
DEFAULT_REFRESH_INTERVAL = 6

MIN_LOOKAHEAD_DAYS = 1
MAX_LOOKAHEAD_DAYS = 30

MIN_REFRESH_INTERVAL = 1
MAX_REFRESH_INTERVAL = 24

API_BASE = "https://api.themoviedb.org/3"

PLATFORMS = ["sensor"]
